"use client"

import SideNavMain from '@/app/[locale]/components/settings/sideNavMain';
import React, { useEffect, useState } from 'react';
import { User, getAuth, onAuthStateChanged } from "firebase/auth";
import { firebaseApp, firebaseAuth } from '@/firebase/config';
import { redirect, useRouter } from 'next/navigation';




// export const metadata = {
//     title: 'Create Next App',
//     // description: 'Generated by create-nx-workspace',
// };
// export const revalidate = 0

export default function SettingsLayout({
    children,
    params: { locale }
}: {
    children?: React.ReactNode;
    params: {
        locale: string;
    };

}) {

    // if (!user222) {
    //     redirect('/')
    // }



    const router = useRouter()
    useEffect(() => {
        const unsubscribe = onAuthStateChanged(firebaseAuth, (user) => {
            console.log('before,user', user)
            if (user) {
                // User is signed in
                console.log("FBUSERSUBS", user)
            } else {
                console.log("nouser")

                router.replace(`/`)
                // User is signed out
                // setUser(null);
            }
        });

        // Cleanup subscription on unmount
        return () => unsubscribe();
    }, []);


    return (
        <main className='settingsWrapp'>
            <SideNavMain locale={locale} />
            {children}
        </main>
    );
}