import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '../scss/main.scss';
import dynamic from 'next/dynamic';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'], display: 'swap' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const AppThemeProvider = dynamic(() => import("../theme/provider"), {
  ssr: false,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const theme = cookies().get("__theme__")?.value || "system";

  return (
    <html lang="en" style={theme !== "system" ? { colorScheme: theme } : {}}>
      <body className={inter.className}>
        <AppThemeProvider enableSystem={false} defaultTheme={theme}>
          {children}
        </AppThemeProvider>
      </body>
    </html>
  )
}
